spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: books-service
          uri: lb://BOOKS-SERVICE
          predicates:
            - Path=/books/**
          filters:
            - name: Token
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-account-service
          uri: lb://USER-ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: model-service
          uri: lb://MODEL-SERVICE
          predicates:
            - Path=/models/**
        - id: location-service
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/locations/**
        - id: asset-service
          uri: lb://ASSET-SERVICE
          predicates:
            - Path=/assets/**
        - id: contract-service
          uri: lb://CONTRACT-SERVICE
          predicates:
            - Path=/contracts/**
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'