spring:
  application:
    name: user-account-service
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true
