spring:
  application:
    name: location-service

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'