spring:
  application:
    name: asset-service
  servlet:
      multipart:
        max-file-size: 500KB
        max-request-size: 500KB
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'